name: Send Instagram DM

on:
  schedule:
    - cron: '15 16 * * *'  # Türkiye saatiyle 23:03 (UTC+3)
  workflow_dispatch:

jobs:
  send_dm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install selenium webdriver-manager

      - name: Create send_dm.py
        run: |
          cat > send_dm.py <<EOF
          from selenium import webdriver
          from selenium.webdriver.common.by import By
          from selenium.webdriver.chrome.options import Options
          import time
          import os

          USERNAME = os.environ['IG_USERNAME']
          PASSWORD = os.environ['IG_PASSWORD']
          RECEIVER = 'muhammed_sozn'
          MESSAGE = 'bu adam niye var'

          options = Options()
          options.add_argument('--headless')
          options.add_argument('--disable-gpu')
          options.add_argument('--no-sandbox')
          options.add_argument('--window-size=1920,1080')
          driver = webdriver.Chrome(options=options)

          try:
              driver.get('https://www.instagram.com/accounts/login/')
              time.sleep(5)
              driver.find_element(By.NAME, 'username').send_keys(USERNAME)
              driver.find_element(By.NAME, 'password').send_keys(PASSWORD)
              driver.find_element(By.XPATH, "//button[@type='submit']").click()
              time.sleep(10)

              try:
                  driver.find_element(By.XPATH, "//button[contains(text(), 'Şimdi Değil')]").click()
              except:
                  pass
              time.sleep(5)

              driver.get(f'https://www.instagram.com/direct/t/{RECEIVER}/')
              time.sleep(10)

              textarea = driver.find_element(By.TAG_NAME, 'textarea')
              textarea.send_keys(MESSAGE)
              time.sleep(1)

              driver.find_element(By.XPATH, "//button[text()='Gönder']").click()
              time.sleep(5)
          finally:
              driver.quit()
          EOF

      - name: Run the bot
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: python send_dm.py
