name: Send Instagram DM

on:
  schedule:
    - cron: '3 20 * * *'  # Türkiye saatiyle 23:03
  workflow_dispatch:

jobs:
  send_dm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Chromium
      run: |
        sudo apt update
        sudo apt install -y chromium-browser

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install selenium

    - name: Write bot file
      run: |
        echo "from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time
import os

username = os.environ['IG_USERNAME']
password = os.environ['IG_PASSWORD']
target_user = 'muhammed_sozn'
message = 'bu adam niye var'

options = Options()
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')

driver = webdriver.Chrome(options=options)

try:
    driver.get('https://www.instagram.com/accounts/login/')
    time.sleep(5)
    driver.find_element(By.NAME, 'username').send_keys(username)
    driver.find_element(By.NAME, 'password').send_keys(password)
    driver.find_element(By.XPATH, \"//button[@type='submit']\").click()
    time.sleep(8)

    driver.get(f'https://www.instagram.com/{target_user}/')
    time.sleep(5)

    driver.find_element(By.XPATH, \"//button[text()='Mesaj gönder']\").click()
    time.sleep(5)

    textarea = driver.find_element(By.TAG_NAME, 'textarea')
    textarea.send_keys(message)
    time.sleep(1)

    driver.find_element(By.XPATH, \"//button[text()='Gönder']\").click()
    time.sleep(3)
finally:
    driver.quit()" > send_dm.py

    - name: Run bot
      env:
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      run: python send_dm.py
